#!/usr/bin/env bash

remove_trailing_whitespace_from_changed_lines() {
    patch=$(mktemp /tmp/remove-trailing-whitespace-patch-XXXXX)
    git diff --cached --no-color --diff-filter=M > "$patch"
    git apply --index --reverse "$patch"
    git apply --index --whitespace=fix "$patch"
    rm "$patch"
}

remove_trailing_whitespace_from_changed_lines > /dev/null 2>&1
